### ISSUE TITLE
Place Focus on 'Word or Phrase' on startup

### ISSUE THREAD

**Issue by kdwk** [johnfactotum/quick-lookup#17] opened 2021-04-17 09:33 UTC
When I open Quick Lookup, the focus is on the 'Language' text field. I have to manually click on the 'Word and Phrase' text field to start searching every time I open the app, which is troublesome

**Comment by johnfactotum** [comment] 2021-04-19 06:25
Duplicate of #11

**Closed by johnfactotum** 2021-04-19 06:25 UTC
