### ISSUE TITLE
Focus the search field by default instead of the language field

### ISSUE THREAD

**Issue by da2x** [johnfactotum/quick-lookup#34] opened 2022-08-11 10:11 UTC
Steps to reproduce:
1. Open the app
2. Just start typing without doing anything else

Expected:
Should enter text into the search/lookup field (the primary action).

Actual:
Enters text into the language-selection field (a secondary action).

Workaround:
Press Tab two times.

Suggested fix:
Swap the two input fields around. That puts the primary action first and you also get the preferred tab-order of search-input -> language-combo-field -> language-combo-button.

Environment:
Version 1.2.0 (via Flathub), KDE Plasma 5.25.4, Wayland, Fedora 36

**Comment by johnfactotum** [comment] 2022-08-11 10:50
Duplicate of #11

**Closed by johnfactotum** 2022-08-11 10:50 UTC
